CREATE CONSTRAINT question_id IF NOT EXISTS
FOR (q:Question)
REQUIRE q.id IS UNIQUE;

CREATE CONSTRAINT answer_id IF NOT EXISTS
FOR (a:Answer)
REQUIRE a.id IS UNIQUE;

CREATE CONSTRAINT concept_name IF NOT EXISTS
FOR (c:Concept)
REQUIRE c.name IS UNIQUE;
